/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddNewTask: typeof import('./components/AddNewTask.vue')['default']
    AddNewTaskForm: typeof import('./components/AddNewTaskForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskList: typeof import('./components/TaskList.vue')['default']
    TodoCategoriesList: typeof import('./components/TodoCategoriesList.vue')['default']
  }
}
